mod arrays;
mod conditional;
mod constants;
mod enums;
mod errors;
mod expression;
mod functions;
mod generics;
mod hash;
mod loops;
mod shadowing;
mod slice;
mod strings;
mod structs;
mod tuples;
mod vars;
mod vec;

fn main() {
    vars::mutability();
    constants::constants();
    shadowing::shadowing();
    tuples::tuples();
    tuples::tup_direct_access();
    arrays::arrays();
    arrays::array_element_access();
    functions::another_function(5);
    functions::plus_one(3);
    expression::expression();
    conditional::conditional();
    loops::loop_label();
    slice::slice_word();
    structs::my_struct();
    vec::vects();
    enums::stubby();
    strings::string_ex();
    hash::get_hashmaps();
    errors::errors();
    generics::largest_number();
}
